config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show]
  resources :articles
  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :confirmable, :validatable

  dragonfly_accessor :avatar do
    default 'public/system/dragonfly/development/avatar.jpg'
  end

  validates :username, presence: true, uniqueness: true

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params
    @article.user_id = current_user.id
    @article.save
    redirect_to articles_path
  end

  def show
    @article = Article.find(params[:id])
  end

  private

    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  respond_to :html, :js

  protected

    def after_update_path_for(resource)
      user_path(current_user)
    end

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

  private

    def sign_up_params
      params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :biography)
    end

    def account_update_params
      params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :current_password, :biography, :avatar)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<h3>New article</h3>

<div class='row'>
  <%= form_for @article, class: 'col s12' do |f| %>
    <div class="row">
      <div class="input-field col s6">
        <%= f.text_field :title %>
        <%= f.label :title %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :content, class: 'materialize-textarea' %>
        <%= f.label :content %>
      </div>
    </div>
    <div class="row">
      <div class="col s12 actions">
        <%= f.submit 'Submit', class: 'waves-effect waves-light btn' %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/index.html.erb
<h3>Find out the lastest posts</h3>

<div class='row'>
  <% @articles.each do |article| %>
      <div class='col s12'>
        <div class='card grey lighten-5 hoverable'>
          <div class='card-content'>
            <span class='card-title'><%= article.title %></span>
            <p class='truncate'><%= article.content %></p>
          </div>
          <div class='card-action'>
            <%= link_to "Author: #{article.user.username}", user_path(article.user) %>
            <%= link_to "#{article.created_at.to_date}", article_path(article) %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div class='row'>
  <div class='col s12'>
    <div class='card grey lighten-5 hoverable'>
      <div class='card-content'>
        <span class='card-title'><%= @article.title %></span>
        <p><%= @article.content %></p>
      </div>
      <div class='card-action'>
        <%= link_to "Author: #{@article.user.username}", user_path(@article.user) %>
        <%= link_to "#{@article.created_at.to_date}", articles_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to 'Homepage', root_path, class: 'brand-logo right' %>
    <ul id="nav-mobile" class="left hide-on-med-and-down">
      <li><%= link_to 'Dashboard', user_path(current_user) if current_user %></li>
      <li><%= link_to 'Articles', articles_path %></li>
      <li><a href="#">JavaScript</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% if notice || alert %>
        <script>
          Materialize.toast('<%= notice || alert %>', 4000);
        </script>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Enter in the sandbox</h1>

<% if current_user %>
  <%= link_to "Log out",  destroy_user_session_path, method: :delete, class: 'waves-effect waves-light btn-large' %>
<% else %>
  <%= link_to "Sign in", new_user_session_path, class: 'waves-effect waves-light btn-large' %>
<% end %>

app/views/users/show.html.erb
<div class="row users">
  <div class="col s12 m7">
    <div class="card big">
      <div class="card-image">
        <%= form_for(@user, url: registration_path(@user), remote: true, html: { method: :put}) do |f| %>
          <i class="material-icons md-36 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Upload picture">publish</i>
          <%= f.file_field :avatar, style: 'display: none', class: 'avatar-upload' %>
        <% end %>
        <%= image_tag @user.avatar.thumb('500x250#').url, class: 'avatar' %>
        <span class="card-title"><%= @user.username %></span>
      </div>
      <div class="card-content">
        <p><%= @user.biography %></p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit profile', edit_user_registration_path %>
        <%= link_to 'Write something', new_article_path %>
      </div>
    </div>
  </div>

  <div class='col s12 m5'>
    <ul class="collapsible" data-collapsible="accordion">
      <% @user.articles.each do |article| %>
        <li>
          <div class="collapsible-header"><i class="material-icons">library_books</i>
            <%= article.title %> - <%= article.created_at.to_date%>
          </div>
          <div class="collapsible-body">
            <span><%= article.content %></span><br>
            <span><%= link_to 'Go to article', article_path(article) %></span>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>